#include "AttackComboBox.h"

AttackComboBox::AttackComboBox( QWidget* parent ) : QComboBox( parent )
{
	// Add all attacks available in Gen 3 ) );
	addItem(tr("No Attack"), QVariant( 0 ) );
	addItem(tr("Pound"), QVariant( 1 ) );
	addItem(tr("Karate Chop"), QVariant( 2 ) );
	addItem(tr("Double Slap"), QVariant( 3 ) );
	addItem(tr("Comet Punch"), QVariant( 4 ) );
	addItem(tr("Mega Punch"), QVariant( 5 ) );
	addItem(tr("Pay Day"), QVariant( 6 ) );
	addItem(tr("Fire Punch"), QVariant( 7 ) );
	addItem(tr("Ice Punch"), QVariant( 8 ) );
	addItem(tr("Thunderpunch"), QVariant( 9 ) );
	addItem(tr("Scratch"), QVariant( 10 ) );
	addItem(tr("Vicegrip"), QVariant( 11 ) );
	addItem(tr("?"), QVariant( 12 ) );
	addItem(tr("Razor Wind"), QVariant( 13 ) );
	addItem(tr("Swords Dance"), QVariant( 14 ) );
	addItem(tr("Cut"), QVariant( 15 ) );
	addItem(tr("Gust"), QVariant( 16 ) );
	addItem(tr("Wing Attack"), QVariant( 17 ) );
	addItem(tr("Whirlwind"), QVariant( 18 ) );
	addItem(tr("Fly"), QVariant( 19 ) );
	addItem(tr("Bind"), QVariant( 20 ) );
	addItem(tr("Slam"), QVariant( 21 ) );
	addItem(tr("Vine Whip"), QVariant( 22 ) );
	addItem(tr("Stomp"), QVariant( 23 ) );
	addItem(tr("Double Kick"), QVariant( 24 ) );
	addItem(tr("Mega Kick"), QVariant( 25 ) );
	addItem(tr("Jump Kick"), QVariant( 26 ) );
	addItem(tr("Rolling Kick"), QVariant( 27 ) );
	addItem(tr("Sand Attack"), QVariant( 28 ) );
	addItem(tr("Headbutt"), QVariant( 29 ) );
	addItem(tr("Horn Attack"), QVariant( 30 ) );
	addItem(tr("Fury Attack"), QVariant( 31 ) );
	addItem(tr("Horn Drill"), QVariant( 32 ) );
	addItem(tr("Tackle"), QVariant( 33 ) );
	addItem(tr("Body Slam"), QVariant( 34 ) );
	addItem(tr("Wrap"), QVariant( 35 ) );
	addItem(tr("Take Down"), QVariant( 36 ) );
	addItem(tr("Thrash"), QVariant( 37 ) );
	addItem(tr("Double-Edge"), QVariant( 38 ) );
	addItem(tr("Tail Whip"), QVariant( 39 ) );
	addItem(tr("Poison Sting"), QVariant( 40 ) );
	addItem(tr("Twineedle"), QVariant( 41 ) );
	addItem(tr("Pin Missile"), QVariant( 42 ) );
	addItem(tr("Leer"), QVariant( 43 ) );
	addItem(tr("Bite"), QVariant( 44 ) );
	addItem(tr("Growl"), QVariant( 45 ) );
	addItem(tr("Roar"), QVariant( 46 ) );
	addItem(tr("Sing"), QVariant( 47 ) );
	addItem(tr("Supersonic"), QVariant( 48 ) );
	addItem(tr("Sonicboom"), QVariant( 49 ) );
	addItem(tr("Disable"), QVariant( 50 ) );
	addItem(tr("Acid"), QVariant( 51 ) );
	addItem(tr("Ember"), QVariant( 52 ) );
	addItem(tr("Flamethrower"), QVariant( 53 ) );
	addItem(tr("Mist"), QVariant( 54 ) );
	addItem(tr("Water Gun"), QVariant( 55 ) );
	addItem(tr("Hydro Pump"), QVariant( 56 ) );
	addItem(tr("Surf"), QVariant( 57 ) );
	addItem(tr("Ice Beam"), QVariant( 58 ) );
	addItem(tr("Blizzard"), QVariant( 59 ) );
	addItem(tr("Psybeam"), QVariant( 60 ) );
	addItem(tr("Bubblebeam"), QVariant( 61 ) );
	addItem(tr("Aurora Beam"), QVariant( 62 ) );
	addItem(tr("Hyper Beam"), QVariant( 63 ) );
	addItem(tr("Peack"), QVariant( 64 ) );
	addItem(tr("Drill Peck"), QVariant( 65 ) );
	addItem(tr("Submission"), QVariant( 66 ) );
	addItem(tr("Low Kick"), QVariant( 67 ) );
	addItem(tr("Counter"), QVariant( 68 ) );
	addItem(tr("Strength"), QVariant( 69 ) );
	addItem(tr("Seismic Toss"), QVariant( 70 ) );
	addItem(tr("Absorb"), QVariant( 71 ) );
	addItem(tr("Mega Drain"), QVariant( 72 ) );
	addItem(tr("Leech Seed"), QVariant( 73 ) );
	addItem(tr("Growth"), QVariant( 74 ) );
	addItem(tr("Razor Leaf"), QVariant( 75 ) );
	addItem(tr("Solarbeam"), QVariant( 76 ) );
	addItem(tr("Poisonpowder"), QVariant( 77 ) );
	addItem(tr("Stun Spore"), QVariant( 78 ) );
	addItem(tr("Sleep Powder"), QVariant( 79 ) );
	addItem(tr("Petal Dance"), QVariant( 80 ) );
	addItem(tr("String Shot"), QVariant( 81 ) );
	addItem(tr("Dragon Rage"), QVariant( 82 ) );
	addItem(tr("Fire Spin"), QVariant( 83 ) );
	addItem(tr("Thundershock"), QVariant( 84 ) );
	addItem(tr("Thunderbolt"), QVariant( 85 ) );
	addItem(tr("Thunder Wave"), QVariant( 86 ) );
	addItem(tr("Thunder"), QVariant( 87 ) );
	addItem(tr("Rock Throw"), QVariant( 88 ) );
	addItem(tr("Earthquake"), QVariant( 89 ) );
	addItem(tr("Fissure"), QVariant( 90 ) );
	addItem(tr("Dig"), QVariant( 91 ) );
	addItem(tr("Toxic"), QVariant( 92 ) );
	addItem(tr("Confusion"), QVariant( 93 ) );
	addItem(tr("Psychic"), QVariant( 94 ) );
	addItem(tr("Hypnosis"), QVariant( 95 ) );
	addItem(tr("Meditate"), QVariant( 96 ) );
	addItem(tr("Agility"), QVariant( 97 ) );
	addItem(tr("Quick Attack"), QVariant( 98 ) );
	addItem(tr("Rage"), QVariant( 99 ) );
	addItem(tr("Teleport"), QVariant( 100 ) );
	addItem(tr("Night Shade"), QVariant( 101 ) );
	addItem(tr("Mimic"), QVariant( 102 ) );
	addItem(tr("Screech"), QVariant( 103 ) );
	addItem(tr("Double Team"), QVariant( 104 ) );
	addItem(tr("Recover"), QVariant( 105 ) );
	addItem(tr("Harden"), QVariant( 106 ) );
	addItem(tr("Minimize"), QVariant( 107 ) );
	addItem(tr("Smokescreen"), QVariant( 108 ) );
	addItem(tr("Confuse Ray"), QVariant( 109 ) );
	addItem(tr("Withdraw"), QVariant( 110 ) );
	addItem(tr("Defense Curl"), QVariant( 111 ) );
	addItem(tr("Barrier"), QVariant( 112 ) );
	addItem(tr("Light Screen"), QVariant( 113 ) );
	addItem(tr("Haze"), QVariant( 114 ) );
	addItem(tr("Reflect"), QVariant( 115 ) );
	addItem(tr("Focus Energy"), QVariant( 116 ) );
	addItem(tr("Bide"), QVariant( 117 ) );
	addItem(tr("Metronome"), QVariant( 118 ) );
	addItem(tr("Mirror Move"), QVariant( 119 ) );
	addItem(tr("Selfdestrust"), QVariant( 120 ) );
	addItem(tr("Egg Bomb"), QVariant( 121 ) );
	addItem(tr("Lick"), QVariant( 122 ) );
	addItem(tr("Smog"), QVariant( 123 ) );
	addItem(tr("Sludge"), QVariant( 124 ) );
	addItem(tr("Bone Club"), QVariant( 125 ) );
	addItem(tr("Fire Blast"), QVariant( 126 ) );
	addItem(tr("Waterfall"), QVariant( 127 ) );
	addItem(tr("Clamp"), QVariant( 128 ) );
	addItem(tr("Swift"), QVariant( 129 ) );
	addItem(tr("Skull Bash"), QVariant( 130 ) );
	addItem(tr("Spike Cannon"), QVariant( 131 ) );
	addItem(tr("Constrict"), QVariant( 132 ) );
	addItem(tr("Amnesia"), QVariant( 133 ) );
	addItem(tr("Kinesis"), QVariant( 134 ) );
	addItem(tr("Softboild"), QVariant( 135 ) );
	addItem(tr("Hi Jump Kick"), QVariant( 136 ) );
	addItem(tr("Glare"), QVariant( 137 ) );
	addItem(tr("Dream Eater"), QVariant( 138 ) );
	addItem(tr("Poison Gas"), QVariant( 139 ) );
	addItem(tr("Barrage"), QVariant( 140 ) );
	addItem(tr("Leech Life"), QVariant( 141 ) );
	addItem(tr("Lovely Kiss"), QVariant( 142 ) );
	addItem(tr("Sky Attack"), QVariant( 143 ) );
	addItem(tr("Transform"), QVariant( 144 ) );
	addItem(tr("Bubble"), QVariant( 145 ) );
	addItem(tr("Dizzy Punch"), QVariant( 146 ) );
	addItem(tr("Spore"), QVariant( 147 ) );
	addItem(tr("Flash"), QVariant( 148 ) );
	addItem(tr("Psywave"), QVariant( 149 ) );
	addItem(tr("Splash"), QVariant( 150 ) );
	addItem(tr("Acid Armor"), QVariant( 151 ) );
	addItem(tr("Crabhammer"), QVariant( 152 ) );
	addItem(tr("Explosion"), QVariant( 153 ) );
	addItem(tr("Fury Swipes"), QVariant( 154 ) );
	addItem(tr("Bonemerang"), QVariant( 155 ) );
	addItem(tr("Rest"), QVariant( 156 ) );
	addItem(tr("Rock Slide"), QVariant( 157 ) );
	addItem(tr("Hyper Fang"), QVariant( 158 ) );
	addItem(tr("Sharpen"), QVariant( 159 ) );
	addItem(tr("Conversion"), QVariant( 160 ) );
	addItem(tr("Tri Attack"), QVariant( 161 ) );
	addItem(tr("Super Fang"), QVariant( 162 ) );
	addItem(tr("Slash"), QVariant( 163 ) );
	addItem(tr("Substiture"), QVariant( 164 ) );
	addItem(tr("Struggle"), QVariant( 165 ) );
	addItem(tr("Sketch"), QVariant( 166 ) );
	addItem(tr("Triple Kick"), QVariant( 167 ) );
	addItem(tr("Thief"), QVariant( 168 ) );
	addItem(tr("Spider Web"), QVariant( 169 ) );
	addItem(tr("Mind Reader"), QVariant( 170 ) );
	addItem(tr("Nightmare"), QVariant( 171 ) );
	addItem(tr("Flame Wheel"), QVariant( 172 ) );
	addItem(tr("Snore"), QVariant( 173 ) );
	addItem(tr("Curse"), QVariant( 174 ) );
	addItem(tr("Flail"), QVariant( 175 ) );
	addItem(tr("Conversion 2"), QVariant( 176 ) );
	addItem(tr("Aeroblast"), QVariant( 177 ) );
	addItem(tr("Cotton Spore"), QVariant( 178 ) );
	addItem(tr("Reversal"), QVariant( 179 ) );
	addItem(tr("Spite"), QVariant( 180 ) );
	addItem(tr("Powder Snow"), QVariant( 181 ) );
	addItem(tr("Protect"), QVariant( 182 ) );
	addItem(tr("Mach Punch"), QVariant( 183 ) );
	addItem(tr("Scary Face"), QVariant( 184 ) );
	addItem(tr("Faint Attack"), QVariant( 185 ) );
	addItem(tr("Sweet Kiss"), QVariant( 186 ) );
	addItem(tr("Belly Drum"), QVariant( 187 ) );
	addItem(tr("Sludge Bomb"), QVariant( 188 ) );
	addItem(tr("Mud-Slap"), QVariant( 189 ) );
	addItem(tr("Octazooka"), QVariant( 190 ) );
	addItem(tr("Spikes"), QVariant( 191 ) );
	addItem(tr("Zap Cannon"), QVariant( 192 ) );
	addItem(tr("Foresight"), QVariant( 193 ) );
	addItem(tr("Destiny Bond"), QVariant( 194 ) );
	addItem(tr("Perish Song"), QVariant( 195 ) );
	addItem(tr("Ice Wind"), QVariant( 196 ) );
	addItem(tr("Detect"), QVariant( 197 ) );
	addItem(tr("Bone Rush"), QVariant( 198 ) );
	addItem(tr("Lock-On"), QVariant( 199 ) );
	addItem(tr("Outrage"), QVariant( 200 ) );
	addItem(tr("Sandstorm"), QVariant( 201 ) );
	addItem(tr("Giga Drain"), QVariant( 202 ) );
	addItem(tr("Endure"), QVariant( 203 ) );
	addItem(tr("Charm"), QVariant( 204 ) );
	addItem(tr("Rollout"), QVariant( 205 ) );
	addItem(tr("False Swipe"), QVariant( 206 ) );
	addItem(tr("Swagger"), QVariant( 207 ) );
	addItem(tr("Milk Drink"), QVariant( 208 ) );
	addItem(tr("Spark"), QVariant( 209 ) );
	addItem(tr("Fury Cutter"), QVariant( 210 ) );
	addItem(tr("Steel Wing"), QVariant( 211 ) );
	addItem(tr("Mean Look"), QVariant( 212 ) );
	addItem(tr("Attract"), QVariant( 213 ) );
	addItem(tr("Sleep Talk"), QVariant( 214 ) );
	addItem(tr("Heal Bell"), QVariant( 215 ) );
	addItem(tr("Return"), QVariant( 216 ) );
	addItem(tr("Present"), QVariant( 217 ) );
	addItem(tr("Frustration"), QVariant( 218 ) );
	addItem(tr("Safeguard"), QVariant( 219 ) );
	addItem(tr("Pain Split"), QVariant( 220 ) );
	addItem(tr("Sacred Fire"), QVariant( 221 ) );
	addItem(tr("Magnitude"), QVariant( 222 ) );
	addItem(tr("Dynamicpunch"), QVariant( 223 ) );
	addItem(tr("Megahorn"), QVariant( 224 ) );
	addItem(tr("Dragonbreath"), QVariant( 225 ) );
	addItem(tr("Baton Pass"), QVariant( 226 ) );
	addItem(tr("Encore"), QVariant( 227 ) );
	addItem(tr("Pursuit"), QVariant( 228 ) );
	addItem(tr("Rapid Spin"), QVariant( 229 ) );
	addItem(tr("Sweet Scent"), QVariant( 230 ) );
	addItem(tr("Iron Tail"), QVariant( 231 ) );
	addItem(tr("Metal Claw"), QVariant( 232 ) );
	addItem(tr("Vital Throw"), QVariant( 233 ) );
	addItem(tr("Morning Sun"), QVariant( 234 ) );
	addItem(tr("Synthesis"), QVariant( 235 ) );
	addItem(tr("Moonlight"), QVariant( 236 ) );
	addItem(tr("Hidden Power"), QVariant( 237 ) );
	addItem(tr("Cross Chop"), QVariant( 238 ) );
	addItem(tr("Twister"), QVariant( 239 ) );
	addItem(tr("Rain Dance"), QVariant( 240 ) );
	addItem(tr("Sunny Day"), QVariant( 241 ) );
	addItem(tr("Crunch"), QVariant( 242 ) );
	addItem(tr("Mirror Coat"), QVariant( 243 ) );
	addItem(tr("Psych Up"), QVariant( 244 ) );
	addItem(tr("Extremespeed"), QVariant( 245 ) );
	addItem(tr("Ancientpower"), QVariant( 246 ) );
	addItem(tr("Shadow Ball"), QVariant( 247 ) );
	addItem(tr("Future Sight"), QVariant( 248 ) );
	addItem(tr("Rock Smash"), QVariant( 249 ) );
	addItem(tr("Whirlpool"), QVariant( 250 ) );
	addItem(tr("Beat Up"), QVariant( 251 ) );
	addItem(tr("Fake Out"), QVariant( 252 ) );
	addItem(tr("Uproar"), QVariant( 253 ) );
	addItem(tr("Stockpile"), QVariant( 254 ) );
	addItem(tr("Spit Up"), QVariant( 255 ) );
	addItem(tr("Swallow"), QVariant( 256 ) );
	addItem(tr("Heat Wave"), QVariant( 257 ) );
	addItem(tr("Hail"), QVariant( 258 ) );
	addItem(tr("Torment"), QVariant( 259 ) );
	addItem(tr("Flatter"), QVariant( 260 ) );
	addItem(tr("Will-O-Wisp"), QVariant( 261 ) );
	addItem(tr("Memento"), QVariant( 262 ) );
	addItem(tr("Facade"), QVariant( 263 ) );
	addItem(tr("Focus Punch"), QVariant( 264 ) );
	addItem(tr("Smellingsalt"), QVariant( 265 ) );
	addItem(tr("Follow Me"), QVariant( 266 ) );
	addItem(tr("Nature Power"), QVariant( 267 ) );
	addItem(tr("Charge"), QVariant( 268 ) );
	addItem(tr("Taunt"), QVariant( 269 ) );
	addItem(tr("Helping Hand"), QVariant( 270 ) );
	addItem(tr("Trick"), QVariant( 271 ) );
	addItem(tr("Role Play"), QVariant( 272 ) );
	addItem(tr("Wish"), QVariant( 273 ) );
	addItem(tr("Assist"), QVariant( 274 ) );
	addItem(tr("Ingrain"), QVariant( 275 ) );
	addItem(tr("Superpower"), QVariant( 276 ) );
	addItem(tr("Magic Coat"), QVariant( 277 ) );
	addItem(tr("Recycle"), QVariant( 278 ) );
	addItem(tr("Revenge"), QVariant( 279 ) );
	addItem(tr("Brick Break"), QVariant( 280 ) );
	addItem(tr("Yawn"), QVariant( 281 ) );
	addItem(tr("Knock Off"), QVariant( 282 ) );
	addItem(tr("Endeavor"), QVariant( 283 ) );
	addItem(tr("Eruption"), QVariant( 284 ) );
	addItem(tr("Skill Swap"), QVariant( 285 ) );
	addItem(tr("Imprison"), QVariant( 286 ) );
	addItem(tr("Refresh"), QVariant( 287 ) );
	addItem(tr("Grudge"), QVariant( 288 ) );
	addItem(tr("Snatch"), QVariant( 289 ) );
	addItem(tr("Secret Power"), QVariant( 290 ) );
	addItem(tr("Dive"), QVariant( 291 ) );
	addItem(tr("Arm Thrust"), QVariant( 292 ) );
	addItem(tr("Camouflage"), QVariant( 293 ) );
	addItem(tr("Tail Glow"), QVariant( 294 ) );
	addItem(tr("Luster Purge"), QVariant( 295 ) );
	addItem(tr("Mist Ball"), QVariant( 296 ) );
	addItem(tr("Featherdance"), QVariant( 297 ) );
	addItem(tr("Teeter Dance"), QVariant( 298 ) );
	addItem(tr("Blaze Kick"), QVariant( 299 ) );
	addItem(tr("Mud Sport"), QVariant( 300 ) );
	addItem(tr("Ice Ball"), QVariant( 301 ) );
	addItem(tr("Needle Arm"), QVariant( 302 ) );
	addItem(tr("Slack Off"), QVariant( 303 ) );
	addItem(tr("Hyper Voice"), QVariant( 304 ) );
	addItem(tr("Poison Fang"), QVariant( 305 ) );
	addItem(tr("Crush Claw"), QVariant( 306 ) );
	addItem(tr("Blast Burn"), QVariant( 307 ) );
	addItem(tr("Hydro Cannon"), QVariant( 308 ) );
	addItem(tr("Meteor Mash"), QVariant( 309 ) );
	addItem(tr("Astonish"), QVariant( 310 ) );
	addItem(tr("Weather Ball"), QVariant( 311 ) );
	addItem(tr("Aromatherapy"), QVariant( 312 ) );
	addItem(tr("Fake Tears"), QVariant( 313 ) );
	addItem(tr("Air Cutter"), QVariant( 314 ) );
	addItem(tr("Overheat"), QVariant( 315 ) );
	addItem(tr("Odor Sleuth"), QVariant( 316 ) );
	addItem(tr("Rock Tomb"), QVariant( 317 ) );
	addItem(tr("Silver Wind"), QVariant( 318 ) );
	addItem(tr("Metal Sound"), QVariant( 319 ) );
	addItem(tr("Grasswhistle"), QVariant( 320 ) );
	addItem(tr("Tickle"), QVariant( 321 ) );
	addItem(tr("Cosmic Power"), QVariant( 322 ) );
	addItem(tr("Water Spout"), QVariant( 323 ) );
	addItem(tr("Signal Beam"), QVariant( 324 ) );
	addItem(tr("Shadow Punch"), QVariant( 325 ) );
	addItem(tr("Extrasensory"), QVariant( 326 ) );
	addItem(tr("Sky Uppercut"), QVariant( 327 ) );
	addItem(tr("Sand Tomb"), QVariant( 328 ) );
	addItem(tr("Sheer Cold"), QVariant( 329 ) );
	addItem(tr("Muddy Water"), QVariant( 330 ) );
	addItem(tr("Bullet Seed"), QVariant( 331 ) );
	addItem(tr("Aerial Ace"), QVariant( 332 ) );
	addItem(tr("Icecle Spear"), QVariant( 333 ) );
	addItem(tr("Iron Defense"), QVariant( 334 ) );
	addItem(tr("Block"), QVariant( 335 ) );
	addItem(tr("Howl"), QVariant( 336 ) );
	addItem(tr("Dragon Claw"), QVariant( 337 ) );
	addItem(tr("Frenzy Plant"), QVariant( 338 ) );
	addItem(tr("Bulk Up"), QVariant( 339 ) );
	addItem(tr("Bounce"), QVariant( 340 ) );
	addItem(tr("Mud Shot"), QVariant( 341 ) );
	addItem(tr("Poison Tail"), QVariant( 342 ) );
	addItem(tr("Cover"), QVariant( 343 ) );
	addItem(tr("Volt Tackle"), QVariant( 344 ) );
	addItem(tr("Magical Leaf"), QVariant( 345 ) );
	addItem(tr("Water Sport"), QVariant( 346 ) );
	addItem(tr("Calm Mind"), QVariant( 347 ) );
	addItem(tr("Leaf Blade"), QVariant( 348 ) );
	addItem(tr("Dragon Dance"), QVariant( 349 ) );
	addItem(tr("Rock Blast"), QVariant( 350 ) );
	addItem(tr("Shock Wave"), QVariant( 351 ) );
	addItem(tr("Water Pulse"), QVariant( 352 ) );
	addItem(tr("Doom Desire"), QVariant( 353 ) );
	addItem(tr("Psycho Boost"), QVariant( 354 ) );
};
                                                        