#include "ItemComboBox.h"

ItemComboBox::ItemComboBox( QWidget* parent ) : QComboBox( parent )
{
	// Add all items available in Gen 3 ) );
	addItem(tr("No Item"), QVariant( 0 ));
	addItem(tr("Master Ball"), QVariant( 1 ));
	addItem(tr("Ultra Ball"), QVariant( 2 ));
	addItem(tr("Great Ball"), QVariant( 3 ));
	addItem(tr("Poke Ball"), QVariant( 4 ));
	addItem(tr("Safari Ball"), QVariant( 5 ));
	addItem(tr("Net Ball"), QVariant( 6 ));
	addItem(tr("Dive Ball"), QVariant( 7 ));
	addItem(tr("Nest Ball"), QVariant( 8 ));
	addItem(tr("Repeat Ball"), QVariant( 9 ));
	addItem(tr("Timer Ball"), QVariant( 10 ));
	addItem(tr("Luxury Ball"), QVariant( 11 ));
	addItem(tr("Premier Ball"), QVariant( 12 ));
	addItem(tr("Potion"), QVariant( 13 ));
	addItem(tr("Antidote"), QVariant( 14 ));
	addItem(tr("Burn Heal"), QVariant( 15 ));
	addItem(tr("Ice Heal"), QVariant( 16 ));
	addItem(tr("Awakening"), QVariant( 17 ));
	addItem(tr("Parlyz Heal"), QVariant( 18 ));
	addItem(tr("Full Restore"), QVariant( 19 ));
	addItem(tr("Max Potion"), QVariant( 20 ));
	addItem(tr("Hyper Potion"), QVariant( 21 ));
	addItem(tr("Super Potion"), QVariant( 22 ));
	addItem(tr("Full Heal"), QVariant( 23 ));
	addItem(tr("Revive"), QVariant( 24 ));
	addItem(tr("Max Revive"), QVariant( 25 ));
	addItem(tr("Fresh Water"), QVariant( 26 ));
	addItem(tr("Soda Pop"), QVariant( 27 ));
	addItem(tr("Lemonade"), QVariant( 28 ));
	addItem(tr("Moomoo Milk"), QVariant( 29 ));
	addItem(tr("Energypowder"), QVariant( 30 ));
	addItem(tr("Energy Root"), QVariant( 31 ));
	addItem(tr("Heal Powder"), QVariant( 32 ));
	addItem(tr("Revival Herb"), QVariant( 33 ));
	addItem(tr("Ether"), QVariant( 34 ));
	addItem(tr("Max Ether"), QVariant( 35 ));
	addItem(tr("Elixir"), QVariant( 36 ));
	addItem(tr("Max Elixir"), QVariant( 37 ));
	addItem(tr("Lava Cookie"), QVariant( 38 ));
	addItem(tr("Blue Flutre"), QVariant( 39 ));
	addItem(tr("Yellow Flute"), QVariant( 40 ));
	addItem(tr("Red Flute"), QVariant( 41 ));
	addItem(tr("Black Flute"), QVariant( 42 ));
	addItem(tr("White Flute"), QVariant( 43 ));
	addItem(tr("Berry Juice"), QVariant( 44 ));
	addItem(tr("Sacred Ash"), QVariant( 45 ));
	addItem(tr("Shoal Salt"), QVariant( 46 ));
	addItem(tr("Shoal Shell"), QVariant( 47 ));
	addItem(tr("Red Shard"), QVariant( 48 ));
	addItem(tr("Blue Shard"), QVariant( 49 ));
	addItem(tr("Yellow Shard"), QVariant( 50 ));
	addItem(tr("Green Shard"), QVariant( 51 ));
	addItem(tr("HP UP"), QVariant( 63 ));
	addItem(tr("Protein"), QVariant( 64 ));
	addItem(tr("Iron"), QVariant( 65 ));
	addItem(tr("Carbos"), QVariant( 66 ));
	addItem(tr("Calcium"), QVariant( 67 ));
	addItem(tr("Rare Candy"), QVariant( 68 ));
	addItem(tr("PP UP"), QVariant( 69 ));
	addItem(tr("Zinc"), QVariant( 70 ));
	addItem(tr("PP MAX"), QVariant( 71 ));
	addItem(tr("Guard Spec"), QVariant( 73 ));
	addItem(tr("Dire Hit"), QVariant( 74 ));
	addItem(tr("X Attack"), QVariant( 75 ));
	addItem(tr("X Defend"), QVariant( 76 ));
	addItem(tr("X Speed"), QVariant( 77 ));
	addItem(tr("X Accuracy"), QVariant( 78 ));
	addItem(tr("X Special"), QVariant( 79 ));
	addItem(tr("Poke Doll"), QVariant( 80 ));
	addItem(tr("Fluffy Tail"), QVariant( 81 ));
	addItem(tr("Super Repel"), QVariant( 83 ));
	addItem(tr("Max Repel"), QVariant( 84 ));
	addItem(tr("Escape Rope"), QVariant( 85 ));
	addItem(tr("Repel"), QVariant( 86 ));
	addItem(tr("Sun Stone"), QVariant( 93 ));
	addItem(tr("Moon Stone"), QVariant( 94 ));
	addItem(tr("Fire Stone"), QVariant( 95 ));
	addItem(tr("Thunderstone"), QVariant( 96 ));
	addItem(tr("Water Stone"), QVariant( 97 ));
	addItem(tr("Leaf Stone"), QVariant( 98 ));
	addItem(tr("Tinymushroom"), QVariant( 103 ));
	addItem(tr("Big Mushroom"), QVariant( 104 ));
	addItem(tr("Pearl"), QVariant( 106 ));
	addItem(tr("Big Pearl"), QVariant( 107 ));
	addItem(tr("Stardust"), QVariant( 108 ));
	addItem(tr("Star Piece"), QVariant( 109 ));
	addItem(tr("Nugget"), QVariant( 110 ));
	addItem(tr("Heart Scale"), QVariant( 111 ));
	addItem(tr("Orange Mail"), QVariant( 121 ));
	addItem(tr("Harbor Mail"), QVariant( 122 ));
	addItem(tr("Glitter Mail"), QVariant( 123 ));
	addItem(tr("Mech Mail"), QVariant( 124 ));
	addItem(tr("Wood Mail"), QVariant( 125 ));
	addItem(tr("Wave Mail"), QVariant( 126 ));
	addItem(tr("Bead Mail"), QVariant( 127 ));
	addItem(tr("Shadow Mail"), QVariant( 128 ));
	addItem(tr("Tropid Mail"), QVariant( 129 ));
	addItem(tr("Dream Mail"), QVariant( 130 ));
	addItem(tr("Fab Mail"), QVariant( 131 ));
	addItem(tr("Retro Mail"), QVariant( 132 ));
	addItem(tr("Cheri Berry"), QVariant( 133 ));
	addItem(tr("Chesto Berry"), QVariant( 134 ));
	addItem(tr("Pecha Berry"), QVariant( 135 ));
	addItem(tr("Rawst Berry"), QVariant( 136 ));
	addItem(tr("Aspear Berry"), QVariant( 137 ));
	addItem(tr("Leppa Berry"), QVariant( 138 ));
	addItem(tr("Orang Berry"), QVariant( 139 ));
	addItem(tr("Persim Berry"), QVariant( 140 ));
	addItem(tr("Lum Berry"), QVariant( 141 ));
	addItem(tr("Sitrus Berry"), QVariant( 142 ));
	addItem(tr("Figy Berry"), QVariant( 143 ));
	addItem(tr("Wiki Berry"), QVariant( 144 ));
	addItem(tr("Mago Berry"), QVariant( 145 ));
	addItem(tr("Aguav Berry"), QVariant( 146 ));
	addItem(tr("Iapapa Berry"), QVariant( 147 ));
	addItem(tr("Razz Berry"), QVariant( 148 ));
	addItem(tr("Bluk Berry"), QVariant( 149 ));
	addItem(tr("Nanab Berry"), QVariant( 150 ));
	addItem(tr("Wepear Berry"), QVariant( 151 ));
	addItem(tr("Pinap Berry"), QVariant( 152 ));
	addItem(tr("Pomeg Berry"), QVariant( 153 ));
	addItem(tr("Kelpsy Berry"), QVariant( 154 ));
	addItem(tr("Qualot Berry"), QVariant( 155 ));
	addItem(tr("Hondew Berry"), QVariant( 156 ));
	addItem(tr("Grepa Berry"), QVariant( 157 ));
	addItem(tr("Tamato Berry"), QVariant( 158 ));
	addItem(tr("Cornn Berry"), QVariant( 159 ));
	addItem(tr("Magost Berry"), QVariant( 160 ));
	addItem(tr("Rabuta Berry"), QVariant( 161 ));
	addItem(tr("Nomel Berry"), QVariant( 162 ));
	addItem(tr("Spelon Berry"), QVariant( 163 ));
	addItem(tr("Pamtre Berry"), QVariant( 164 ));
	addItem(tr("Watmel Berry"), QVariant( 165 ));
	addItem(tr("Durin Berry"), QVariant( 166 ));
	addItem(tr("Belue Berry"), QVariant( 167 ));
	addItem(tr("Liechi Berry"), QVariant( 168 ));
	addItem(tr("Ganlon Berry"), QVariant( 169 ));
	addItem(tr("Salac Berry"), QVariant( 170 ));
	addItem(tr("Petaya Berry"), QVariant( 171 ));
	addItem(tr("Apicot Berry"), QVariant( 172 ));
	addItem(tr("Lansat Berry"), QVariant( 173 ));
	addItem(tr("Starf Berry"), QVariant( 174 ));
	addItem(tr("Enigma Berry"), QVariant( 175 ));
	addItem(tr("Brightpowder"), QVariant( 179 ));
	addItem(tr("White Herb"), QVariant( 180 ));
	addItem(tr("Macho Brace"), QVariant( 181 ));
	addItem(tr("Exp. Share"), QVariant( 182 ));
	addItem(tr("Quick Claw"), QVariant( 183 ));
	addItem(tr("Soothe Bell"), QVariant( 184 ));
	addItem(tr("Mental Herb"), QVariant( 185 ));
	addItem(tr("Choice Band"), QVariant( 186 ));
	addItem(tr("King's Rock"), QVariant( 187 ));
	addItem(tr("Silverpowder"), QVariant( 188 ));
	addItem(tr("Amulet Coin"), QVariant( 189 ));
	addItem(tr("Cleanse Tag"), QVariant( 190 ));
	addItem(tr("Soul Dew"), QVariant( 191 ));
	addItem(tr("Deep Sea Tooth"), QVariant( 192 ));
	addItem(tr("Deep Sea Scale"), QVariant( 193 ));
	addItem(tr("Smoke Ball"), QVariant( 194 ));
	addItem(tr("Everstone"), QVariant( 195 ));
	addItem(tr("Focus Band"), QVariant( 196 ));
	addItem(tr("Lucky Egg"), QVariant( 197 ));
	addItem(tr("Scope Lens"), QVariant( 198 ));
	addItem(tr("Metal Coat"), QVariant( 199 ));
	addItem(tr("Leftovers"), QVariant( 200 ));
	addItem(tr("Dragon Scale"), QVariant( 201 ));
	addItem(tr("Light Ball"), QVariant( 202 ));
	addItem(tr("Soft Sand"), QVariant( 203 ));
	addItem(tr("Hard Stone"), QVariant( 204 ));
	addItem(tr("Miracle Seed"), QVariant( 205 ));
	addItem(tr("BlackGlasses"), QVariant( 206 ));
	addItem(tr("Black Belt"), QVariant( 207 ));
	addItem(tr("Magnet"), QVariant( 208 ));
	addItem(tr("Mystic Water"), QVariant( 209 ));
	addItem(tr("Sharp Beak"), QVariant( 210 ));
	addItem(tr("Poison Barb"), QVariant( 213 ));
	addItem(tr("Never Melt Ice"), QVariant( 214 ));
	addItem(tr("Spell Tag"), QVariant( 215 ));
	addItem(tr("Twisted Spoon"), QVariant( 216 ));
	addItem(tr("Charcoal"), QVariant( 217 ));
	addItem(tr("Dragon Fang"), QVariant( 218 ));
	addItem(tr("Silk Scarf"), QVariant( 219 ));
	addItem(tr("Up-Grade"), QVariant( 220 ));
	addItem(tr("Shell Bell"), QVariant( 221 ));
	addItem(tr("Sea Incense"), QVariant( 222 ));
	addItem(tr("Lax Incense"), QVariant( 223 ));
	addItem(tr("Lucky Punch"), QVariant( 224 ));
	addItem(tr("Metal Powder"), QVariant( 225 ));
	addItem(tr("Thick Club"), QVariant( 226 ));
	addItem(tr("Stick"), QVariant( 227 ));
};
                                                        